var console_project = "My first console project";
console.log(console_project);
var first_name = "Pratyush";
console.log(first_name);
var last_name = " Goyal";
console.log(last_name);
var full_name = first_name.concat(last_name);
console.log(full_name);
var w = 57;
console.log(w);
var x = 1778;
console.log(x);
var y = 1930;
console.log(y);
var z = 2047;
console.log(z);
var add = x + y;
console.log(add);
var subtract = z - w;
console.log(subtract);
var multiply = w * y;
console.log(multiply);
var divide = x / z;
console.log(divide);